### PR TITLE
b1-Indrajeet-pala

### PR DESCRIPTION
**Pull request by indrajeetpala19**

### CODE REVIEW

**Comment by Eerie16** [comment]
Change Requested: The last line is an extra and is not required

**Comment by Eerie16** [comment]
ALL OK!

**Comment by Eerie16** [comment]
Change Requested : email id is incorrect

**Comment by indrajeetpala19** [comment]
Sir, the email ID is correct and I am receiving your comment notifications on the same ID as mentioned

**Comment by Eerie16** [comment]
should it not be itbhu.ac.in instead of iitbhu.ac.in ? And mai sir nahi hu!

**Comment by indrajeetpala19** [comment]
You can change the domain from itbhu to iitbhu

**Comment by Eerie16** [comment]
ALL OK!

**Pull request merged**
